from enum import Enum
from typing import Any


class MethodOptionType(Enum):
    BOOLEAN = ...
    INTEGER = ...
    FLOATING_POINT = ...
    STRING = ...


class PrerequisiteIssueKind(Enum):
    INVALID_OPTIONS = ...
    MISSING_FEATURE = ...
    INVALID_GEOMETRY = ...
    UNSUPPORTED_MOLECULE = ...
    MISSING_PARAMETERS = ...
    PARAMETER_CLASSIFICATION_FAILED = ...


class ExecutionAvailability(Enum):
    AVAILABLE = ...
    AVAILABLE_WITH_WARNING = ...
    UNSUPPORTED = ...


class ExecutionIssueKind(Enum):
    RESOURCE_THRESHOLD_EXCEEDED = ...
    UNSUPPORTED_EXECUTION_MODE = ...


def _method_descriptors() -> list[dict[str, Any]]: ...
