from typing import Any


class _NativeParameterCatalog:
    @property
    def size(self) -> int: ...

    def _descriptors(self) -> list[dict[str, Any]]: ...


def _load_parameter_catalog(directory: str) -> _NativeParameterCatalog: ...
def _load_parameter_set(path: str) -> _NativeParameterCatalog: ...
def _load_parameter_sets(directory: str) -> list[_NativeParameterCatalog]: ...
def _load_parameter_catalog_from_sets(
    parameter_sets: list[_NativeParameterCatalog],
) -> _NativeParameterCatalog: ...
