from .._payloads import ParameterSetDescriptorPayload

class _NativeParameterCatalog:
    def _descriptors(self) -> list[ParameterSetDescriptorPayload]: ...

def _load_parameter_catalog(directory: str) -> _NativeParameterCatalog: ...
