include("${CMAKE_CURRENT_LIST_DIR}/support/test_cli.cmake")

run_cli(missing_subcommand 2)
run_cli(missing_required_argument 2 calculate "${CHARGEFW_INPUT}")
run_cli(invalid_threads 2 calculate --threads not-a-count "${CHARGEFW_INPUT}" output)
run_cli(unknown_option 2 calculate --unknown-option "${CHARGEFW_INPUT}" output)
run_cli(unknown_method 2 methods not-a-method)
run_cli(unknown_parameter_set 2 parameters not-a-parameter-set)
run_cli(unknown_parameter_method 2 parameters --method not-a-method)
run_cli(parameter_filter_and_detail 2 parameters --method qeq QEq_original)
run_cli(method_option_preserves_positionals 0 applicability --method-option peoe.iters=8
        "${CHARGEFW_INPUT}")

run_cli(help 0 --help)
run_cli(calculate_help 0 calculate --help)
run_cli(inspect 0 inspect "${CHARGEFW_INPUT}")
run_cli(applicable 0 applicability --method formal "${CHARGEFW_INPUT}")
run_cli(inapplicable 0 applicability --method smpqeq "${CHARGEFW_INPUT}")
run_cli(methods 0 methods)
run_cli(method_details 0 methods eem)
run_cli(parameters 0 parameters)
run_cli(parameter_filter 0 parameters --method qeq)
run_cli(parameter_details 0 parameters QEq_original)
