#include <chargefw/adapters/charge_result.h>
#include <chargefw/adapters/native/mol2_input.h>
#include <chargefw/adapters/native/mol2_output.h>
#include <chargefw/charges/atomic_charges.h>
#include <chargefw/charges/charge_collection.h>
#include <chargefw/core/atom.h>
#include <chargefw/core/bond.h>
#include <chargefw/core/conformer.h>
#include <chargefw/core/molecule.h>
#include <snitch/snitch.hpp>

#include <limits>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace {

namespace adapters = chargefw::adapters;
namespace charges = chargefw::charges;
namespace core = chargefw::core;
namespace mol2_input = chargefw::adapters::native::mol2_input;
namespace mol2_output = chargefw::adapters::native::mol2_output;

auto generated_record() -> adapters::ImportedMoleculeRecord {
    return {.molecule =
                core::Molecule{{core::Atom{6, 0, "C1"}, core::Atom{8, -1, "O1"}},
                               {core::Bond{0, 1, core::BondOrder::DOUBLE}},
                               {core::Conformer{{core::Position{0.0, 0.0, 0.0},
                                                 core::Position{1.23456789012345, 0.0, 0.0}}},
                                core::Conformer{{core::Position{0.1, 0.0, 0.0},
                                                 core::Position{1.33456789012345, 0.0, 0.0}}}},
                               "carbonyl"},
            .identity = {.source = "input", .record_id = "record"}};
}

auto calculation_result(std::vector<adapters::ImportedMoleculeRecord> records,
                        charges::ChargeSet charge_set) -> adapters::ChargeCalculationResult {
    const auto method_id = std::string{charge_set.method_id()};
    const auto parameter_set_id = charge_set.parameter_set_id().transform(
        [](const std::string_view value) { return std::string{value}; });
    return adapters::make_charge_calculation_result(
        std::move(records), {},
        {.charges = std::move(charge_set),
         .effective = chargefw::calculation::EffectiveCalculation{
             .method_id = method_id,
             .parameter_set_id = parameter_set_id,
             .execution_policy = chargefw::calculation::ExecutionPolicy{}}});
}

[[nodiscard]] auto occurrences(const std::string_view text, const std::string_view value)
    -> std::size_t {
    std::size_t result = 0;
    for (auto position = text.find(value); position != std::string_view::npos;
         position = text.find(value, position + value.size())) {
        ++result;
    }
    return result;
}

} // namespace

TEST_CASE("result-owned MOL2 writes every conformer with its charges", "[adapters][mol2]") {
    const auto result = calculation_result(
        {generated_record()},
        charges::ChargeSet{
            "qeq",
            {{.target = {.molecule_index = 0, .conformer_index = 0},
              .charges = charges::AtomicCharges{{0.123456789012345, -0.123456789012345}}},
             {.target = {.molecule_index = 0, .conformer_index = 1},
              .charges = charges::AtomicCharges{{0.25, -0.25}}}},
            "qeq-default"});
    auto output = std::ostringstream{};
    mol2_output::Mol2Writer{output}.write(result, "test");
    const auto text = output.str();

    CHECK(occurrences(text, "@<TRIPOS>MOLECULE") == 2);
    CHECK(text.contains("record_conformer_1"));
    CHECK(text.contains("record_conformer_2"));
    CHECK(text.contains("1.23456789012345"));
    CHECK(text.contains("Generated by ChargeFW test"));
    CHECK(text.contains("; method=qeq; parameter_set=qeq-default"));
    CHECK(text.contains("@<TRIPOS>BOND\n1 1 2 2"));
    CHECK(occurrences(text, "@<TRIPOS>SUBSTRUCTURE\n1 UNL 1") == 2);
    const auto second_record = text.find("@<TRIPOS>MOLECULE", 1);
    REQUIRE(second_record != std::string::npos);
    const auto first_text = std::string_view{text}.substr(0, second_record);
    const auto second_text = std::string_view{text}.substr(second_record);
    CHECK(first_text.contains(" 0.123456789012345\n"));
    CHECK_FALSE(first_text.contains(" 0.25\n"));
    CHECK(second_text.contains(" 0.25\n"));
    CHECK_FALSE(second_text.contains(" 0.123456789012345\n"));

    auto round_trip_stream = std::istringstream{text};
    auto reader = mol2_input::Mol2Reader{round_trip_stream};
    const auto first = reader.next();
    const auto second = reader.next();
    REQUIRE(first.has_value());
    REQUIRE(second.has_value());
    CHECK(first->identity.record_id == "record_conformer_1");
    CHECK(second->identity.record_id == "record_conformer_2");
    CHECK(first->molecule.atom_count() == 2);
    CHECK(second->molecule.bond_count() == 1);
    CHECK(first->molecule.conformer(0)[1].x == 1.23456789012345);
    CHECK(second->molecule.conformer(0)[1].x == 1.33456789012345);
    CHECK_FALSE(reader.next().has_value());
}

TEST_CASE("result-owned MOL2 broadcasts molecule charges to retained conformers",
          "[adapters][mol2]") {
    auto second = generated_record();
    second.identity.record_id = "second";
    const auto result = calculation_result(
        {generated_record(), std::move(second)},
        charges::ChargeSet{
            "formal",
            {{.target = {.molecule_index = 0}, .charges = charges::AtomicCharges{{0.25, -0.25}}},
             {.target = {.molecule_index = 1}, .charges = charges::AtomicCharges{{0.5, -0.5}}}}});
    auto output = std::ostringstream{};
    mol2_output::Mol2Writer{output}.write(result);

    CHECK(occurrences(output.str(), " 0.25\n") == 2);
    CHECK(occurrences(output.str(), " -0.25\n") == 2);
    CHECK(occurrences(output.str(), " 0.5\n") == 2);
    CHECK(occurrences(output.str(), " -0.5\n") == 2);
}

TEST_CASE("result-owned MOL2 rejects failed results and invalid values before output",
          "[adapters][mol2]") {
    {
        const auto cancelled = adapters::make_charge_calculation_result(
            {generated_record()}, {},
            {.status = chargefw::calculation::ExecutionStatus::cancelled});
        auto output = std::ostringstream{};
        CHECK_THROWS_AS(mol2_output::Mol2Writer{output}.write(cancelled), std::invalid_argument);
        CHECK(output.str().empty());
    }

    {
        auto record = generated_record();
        record.molecule = core::Molecule{{core::Atom{6}, core::Atom{8}}};
        const auto missing = calculation_result(
            {std::move(record)},
            charges::ChargeSet{"formal",
                               {{.target = {.molecule_index = 0},
                                 .charges = charges::AtomicCharges{{0.0, 0.0}}}}});
        auto output = std::ostringstream{};
        CHECK_THROWS_AS(mol2_output::Mol2Writer{output}.write(missing), std::invalid_argument);
        CHECK(output.str().empty());
    }

    {
        auto record = generated_record();
        record.molecule = core::Molecule{{}, {}, {core::Conformer{{}}}};
        const auto empty = calculation_result(
            {std::move(record)}, charges::ChargeSet{"formal",
                                                    {{.target = {.molecule_index = 0},
                                                      .charges = charges::AtomicCharges{{}}}}});
        auto output = std::ostringstream{};
        CHECK_THROWS_AS(mol2_output::Mol2Writer{output}.write(empty), std::invalid_argument);
        CHECK(output.str().empty());
    }

    {
        auto record = generated_record();
        record.molecule = core::Molecule{
            {core::Atom{6}, core::Atom{8}},
            {},
            {core::Conformer{{{.x = std::numeric_limits<double>::infinity(), .y = 0.0, .z = 0.0},
                              {.x = 1.0, .y = 0.0, .z = 0.0}}}}};
        const auto nonfinite_coordinates = calculation_result(
            {std::move(record)},
            charges::ChargeSet{"formal",
                               {{.target = {.molecule_index = 0, .conformer_index = 0},
                                 .charges = charges::AtomicCharges{{0.0, 0.0}}}}});
        auto output = std::ostringstream{};
        CHECK_THROWS_AS(mol2_output::Mol2Writer{output}.write(nonfinite_coordinates),
                        std::invalid_argument);
        CHECK(output.str().empty());
    }
}
