"""ChargeFW Python API."""

from ._chargefw import version as _native_version
from .calculation import (
    ApplicabilityReport,
    ApplicableCandidate,
    Assessment,
    AssessmentReport,
    CalculationCancelledError,
    CalculationOptions,
    CalculationResult,
    CalculationTimings,
    ChargeCorrectionPolicy,
    ChargeFWError,
    EffectiveCalculation,
    ExecutionMode,
    ExecutionPolicy,
    ExecutionSelectionKind,
    ExecutionStatus,
    InvalidInputError,
    NoExecutablePlanError,
    NumericalFailureError,
    RejectedCandidate,
    assess,
    calculate,
    methods,
    parameter_sets,
)
from .charges import ChargeAssignment
from .core import Molecule, MoleculeCollection, SourceIdentity
from ._methods import (
    ExecutionAssessment,
    ExecutionAvailability,
    ExecutionIssue,
    ExecutionIssueKind,
    MethodCatalog,
    MethodDescriptor,
    MethodOptionCatalog,
    MethodOptionDescriptor,
    MethodOptionType,
    PrerequisiteIssue,
    PrerequisiteIssueKind,
)
from ._parameters import (
    ParameterSetCatalog,
    ParameterSetDescriptor,
)

__version__ = _native_version()

__all__ = [
    "__version__",
    "Molecule",
    "MoleculeCollection",
    "SourceIdentity",
    "CalculationOptions",
    "ChargeAssignment",
    "CalculationResult",
    "Assessment",
    "assess",
    "calculate",
    "methods",
    "parameter_sets",
    "ChargeFWError",
    "InvalidInputError",
    "NoExecutablePlanError",
    "NumericalFailureError",
    "CalculationCancelledError",
    "ExecutionSelectionKind",
    "ExecutionMode",
    "ChargeCorrectionPolicy",
    "ExecutionStatus",
    "PrerequisiteIssueKind",
    "ExecutionAvailability",
    "ExecutionIssueKind",
    "PrerequisiteIssue",
    "ExecutionIssue",
    "ExecutionAssessment",
    "ExecutionPolicy",
    "ApplicableCandidate",
    "RejectedCandidate",
    "ApplicabilityReport",
    "EffectiveCalculation",
    "CalculationTimings",
    "AssessmentReport",
    "MethodOptionType",
    "MethodOptionCatalog",
    "MethodOptionDescriptor",
    "MethodCatalog",
    "MethodDescriptor",
    "ParameterSetCatalog",
    "ParameterSetDescriptor",
]
